apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-blob-fuse-sc
provisioner: blob.csi.azure.com
parameters:
  resourceGroup: <my-resource-group-name> # Change this to the name of the Azure Resource Group.
  storageAccount: <my-storage-account-name> # Change this to the name of the Azure Storage Account.
  protocol: fuse
  containerName: <my-container-name> # Change this to the name of the Azure Storage Container.
  isHnsEnabled: 'true'
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - -o allow_other
  - --attr-timeout=20
  - --cache-size-mb=1000 # Default will be 80% of available memory, eviction will happen beyond that.
  - --cancel-list-on-mount-seconds=10 # prevent billing charges on mounting
  - --entry-timeout=20
  - --file-cache-timeout=120
  - --log-level=LOG_WARNING # LOG_WARNING, LOG_INFO, LOG_DEBUG
  - --negative-timeout=20
  - --use-attr-cache=true
