apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-blob-nfs-pv
spec:
  capacity:
    storage: 1Pi # While the Kubernetes API capacity attribute is mandatory, this value isn't used by the Azure Blob storage CSI driver because you can flexibly write data until you reach your storage account's capacity limit. The value of the capacity attribute is used only for size matching between PersistentVolumes and PersistenVolumeClaims. We recommend using a fictitious high value. The pod sees a mounted volume with a fictitious size of 5 Petabytes.
  accessModes:
    - ReadWriteMany # Allow our many singleuser nodes to read and write to the volume.
  persistentVolumeReclaimPolicy: Retain # Keep the volume after the PVC is deleted.
  storageClassName: azure-blob-nfs-sc
  mountOptions:
    - nconnect=4
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: <my-storage-account-name>_users # Change this to a combination of the name of the Azure Storage Account and Container.
    volumeAttributes:
      resourceGroup: <my-resource-group-name> # Change this to the name of the Azure Resource Group.
      storageAccount: <my-storage-account-name> # Change this to the name of the Azure Storage Account.
      containerName: users
      protocol: nfs
      mountPermisions: '0750'
